// Code generated by hertz generator.

package http

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	httpmodel "github.com/zeefan1555/symphony-go/internal/control/hertzgen/model/control/http"
	model "github.com/zeefan1555/symphony-go/internal/control/hertzgen/model/control/model"
)

// GetScaffold .
// @router /api/v1/scaffold [GET]
func GetScaffold(ctx context.Context, c *app.RequestContext) {
	var err error
	var req model.Empty
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	status, err := getControlService().GetScaffold(ctx)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}
	resp := &model.ScaffoldStatus{Status: status.Status}

	c.JSON(consts.StatusOK, resp)
}

// GetState .
// @router /api/v1/state [GET]
func GetState(ctx context.Context, c *app.RequestContext) {
	var err error
	var req model.Empty
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := getControlService().GetState(ctx)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// GetIssue .
// @router /api/v1/:issue_identifier [GET]
func GetIssue(ctx context.Context, c *app.RequestContext) {
	var err error
	var req httpmodel.IssueRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &model.ErrorEnvelope{Error: &model.ErrorDetail{
			Code:    "invalid_issue_identifier",
			Message: err.Error(),
		}})
		return
	}

	resp, err := getControlService().GetIssue(ctx, req.IssueIdentifier)
	if err != nil {
		envelope, status := ErrorEnvelope(err)
		c.JSON(status, envelope)
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// GetRefreshUnsupported .
// @router /api/v1/refresh [GET]
func GetRefreshUnsupported(ctx context.Context, c *app.RequestContext) {
	var err error
	var req model.Empty
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &model.ErrorEnvelope{Error: &model.ErrorDetail{
			Code:    "invalid_request",
			Message: err.Error(),
		}})
		return
	}

	c.JSON(consts.StatusMethodNotAllowed, &model.ErrorEnvelope{Error: &model.ErrorDetail{
		Code:    "unsupported_method",
		Message: "use POST /api/v1/refresh",
	}})
}

// PostRefresh .
// @router /api/v1/refresh [POST]
func PostRefresh(ctx context.Context, c *app.RequestContext) {
	var err error
	var req model.Empty
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &model.ErrorEnvelope{Error: &model.ErrorDetail{
			Code:    "invalid_request",
			Message: err.Error(),
		}})
		return
	}

	resp, err := getControlService().Refresh(ctx)
	if err != nil {
		envelope, status := ErrorEnvelope(err)
		c.JSON(status, envelope)
		return
	}

	c.JSON(consts.StatusAccepted, resp)
}
