// Code generated by hertz generator.

package http

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	model "github.com/zeefan1555/symphony-go/internal/control/hertzgen/model/control/model"
)

// GetScaffold .
// @router /api/v1/scaffold [GET]
func GetScaffold(ctx context.Context, c *app.RequestContext) {
	var err error
	var req model.Empty
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	status, err := getControlService().GetScaffold(ctx)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}
	resp := &model.ScaffoldStatus{Status: status.Status}

	c.JSON(consts.StatusOK, resp)
}

// GetState .
// @router /api/v1/state [GET]
func GetState(ctx context.Context, c *app.RequestContext) {
	var err error
	var req model.Empty
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := getControlService().GetState(ctx)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	c.JSON(consts.StatusOK, resp)
}
