// Code generated by hertz generator.

package api

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	common "github.com/zeefan1555/symphony-go/biz/model/common"
	control "github.com/zeefan1555/symphony-go/biz/model/control"
	orchestrator "github.com/zeefan1555/symphony-go/biz/model/orchestrator"
	"github.com/zeefan1555/symphony-go/internal/control/hertzhook"
)

// GetScaffold .
// @router /api/v1/control/get-scaffold [POST]
func GetScaffold(ctx context.Context, c *app.RequestContext) {
	var err error
	var req control.GetScaffoldReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	status, err := hertzhook.CurrentService().GetScaffold(ctx)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}
	resp := &control.GetScaffoldResp{Status: status.Status}

	c.JSON(consts.StatusOK, resp)
}

// GetState .
// @router /api/v1/control/get-state [POST]
func GetState(ctx context.Context, c *app.RequestContext) {
	var err error
	var req control.GetStateReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	state, err := hertzhook.CurrentService().GetState(ctx)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}
	resp := &control.GetStateResp{State: state}

	c.JSON(consts.StatusOK, resp)
}

// Refresh .
// @router /api/v1/control/refresh [POST]
func Refresh(ctx context.Context, c *app.RequestContext) {
	var err error
	var req control.RefreshReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := hertzhook.CurrentService().Refresh(ctx)
	if err != nil {
		envelope, status := hertzhook.ErrorEnvelope(err)
		c.JSON(status, envelope)
		return
	}

	c.JSON(consts.StatusAccepted, resp)
}

// GetIssue .
// @router /api/v1/control/get-issue [POST]
func GetIssue(ctx context.Context, c *app.RequestContext) {
	var err error
	var req control.GetIssueReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &common.ErrorEnvelope{Error: &common.ErrorDetail{
			Code:    "invalid_issue_identifier",
			Message: err.Error(),
		}})
		return
	}

	issue, err := hertzhook.CurrentService().GetIssue(ctx, req.IssueIdentifier)
	if err != nil {
		envelope, status := hertzhook.ErrorEnvelope(err)
		c.JSON(status, envelope)
		return
	}
	resp := &control.GetIssueResp{Issue: issue}

	c.JSON(consts.StatusOK, resp)
}

// ProjectIssueRun .
// @router /api/v1/orchestrator/project-issue-run [POST]
func ProjectIssueRun(ctx context.Context, c *app.RequestContext) {
	var err error
	var req orchestrator.ProjectIssueRunReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &common.ErrorEnvelope{Error: &common.ErrorDetail{
			Code:    "invalid_issue_identifier",
			Message: err.Error(),
		}})
		return
	}

	resp, err := hertzhook.CurrentService().ProjectIssueRun(ctx, req.IssueIdentifier)
	if err != nil {
		envelope, status := hertzhook.ErrorEnvelope(err)
		c.JSON(status, envelope)
		return
	}

	c.JSON(consts.StatusOK, resp)
}
