// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package http

import (
	"context"
	"fmt"
	"github.com/apache/thrift/lib/go/thrift"
	"github.com/zeefan1555/symphony-go/internal/control/hertzgen/model/control/model"
)

type ControlPlane interface {
	GetScaffold(ctx context.Context, request *model.Empty) (r *model.ScaffoldStatus, err error)
}

type ControlPlaneClient struct {
	c thrift.TClient
}

func NewControlPlaneClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *ControlPlaneClient {
	return &ControlPlaneClient{
		c: thrift.NewTStandardClient(f.GetProtocol(t), f.GetProtocol(t)),
	}
}

func NewControlPlaneClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *ControlPlaneClient {
	return &ControlPlaneClient{
		c: thrift.NewTStandardClient(iprot, oprot),
	}
}

func NewControlPlaneClient(c thrift.TClient) *ControlPlaneClient {
	return &ControlPlaneClient{
		c: c,
	}
}

func (p *ControlPlaneClient) Client_() thrift.TClient {
	return p.c
}

func (p *ControlPlaneClient) GetScaffold(ctx context.Context, request *model.Empty) (r *model.ScaffoldStatus, err error) {
	var _args ControlPlaneGetScaffoldArgs
	_args.Request = request
	var _result ControlPlaneGetScaffoldResult
	if err = p.Client_().Call(ctx, "GetScaffold", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

type ControlPlaneProcessor struct {
	processorMap map[string]thrift.TProcessorFunction
	handler      ControlPlane
}

func (p *ControlPlaneProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
	p.processorMap[key] = processor
}

func (p *ControlPlaneProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
	processor, ok = p.processorMap[key]
	return processor, ok
}

func (p *ControlPlaneProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
	return p.processorMap
}

func NewControlPlaneProcessor(handler ControlPlane) *ControlPlaneProcessor {
	self := &ControlPlaneProcessor{handler: handler, processorMap: make(map[string]thrift.TProcessorFunction)}
	self.AddToProcessorMap("GetScaffold", &controlPlaneProcessorGetScaffold{handler: handler})
	return self
}
func (p *ControlPlaneProcessor) Process(ctx context.Context, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	name, _, seqId, err := iprot.ReadMessageBegin()
	if err != nil {
		return false, err
	}
	if processor, ok := p.GetProcessorFunction(name); ok {
		return processor.Process(ctx, seqId, iprot, oprot)
	}
	iprot.Skip(thrift.STRUCT)
	iprot.ReadMessageEnd()
	x := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function "+name)
	oprot.WriteMessageBegin(name, thrift.EXCEPTION, seqId)
	x.Write(oprot)
	oprot.WriteMessageEnd()
	oprot.Flush(ctx)
	return false, x
}

type controlPlaneProcessorGetScaffold struct {
	handler ControlPlane
}

func (p *controlPlaneProcessorGetScaffold) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	args := ControlPlaneGetScaffoldArgs{}
	if err = args.Read(iprot); err != nil {
		iprot.ReadMessageEnd()
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
		oprot.WriteMessageBegin("GetScaffold", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return false, err
	}

	iprot.ReadMessageEnd()
	var err2 error
	result := ControlPlaneGetScaffoldResult{}
	var retval *model.ScaffoldStatus
	if retval, err2 = p.handler.GetScaffold(ctx, args.Request); err2 != nil {
		x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing GetScaffold: "+err2.Error())
		oprot.WriteMessageBegin("GetScaffold", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return true, err2
	} else {
		result.Success = retval
	}
	if err2 = oprot.WriteMessageBegin("GetScaffold", thrift.REPLY, seqId); err2 != nil {
		err = err2
	}
	if err2 = result.Write(oprot); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.Flush(ctx); err == nil && err2 != nil {
		err = err2
	}
	if err != nil {
		return
	}
	return true, err
}

type ControlPlaneGetScaffoldArgs struct {
	Request *model.Empty `thrift:"request,1"`
}

func NewControlPlaneGetScaffoldArgs() *ControlPlaneGetScaffoldArgs {
	return &ControlPlaneGetScaffoldArgs{}
}

func (p *ControlPlaneGetScaffoldArgs) InitDefault() {
}

var ControlPlaneGetScaffoldArgs_Request_DEFAULT *model.Empty

func (p *ControlPlaneGetScaffoldArgs) GetRequest() (v *model.Empty) {
	if !p.IsSetRequest() {
		return ControlPlaneGetScaffoldArgs_Request_DEFAULT
	}
	return p.Request
}

var fieldIDToName_ControlPlaneGetScaffoldArgs = map[int16]string{
	1: "request",
}

func (p *ControlPlaneGetScaffoldArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *ControlPlaneGetScaffoldArgs) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_ControlPlaneGetScaffoldArgs[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *ControlPlaneGetScaffoldArgs) ReadField1(iprot thrift.TProtocol) error {
	_field := model.NewEmpty()
	if err := _field.Read(iprot); err != nil {
		return err
	}
	p.Request = _field
	return nil
}

func (p *ControlPlaneGetScaffoldArgs) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("GetScaffold_args"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *ControlPlaneGetScaffoldArgs) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("request", thrift.STRUCT, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := p.Request.Write(oprot); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *ControlPlaneGetScaffoldArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ControlPlaneGetScaffoldArgs(%+v)", *p)

}

type ControlPlaneGetScaffoldResult struct {
	Success *model.ScaffoldStatus `thrift:"success,0,optional"`
}

func NewControlPlaneGetScaffoldResult() *ControlPlaneGetScaffoldResult {
	return &ControlPlaneGetScaffoldResult{}
}

func (p *ControlPlaneGetScaffoldResult) InitDefault() {
}

var ControlPlaneGetScaffoldResult_Success_DEFAULT *model.ScaffoldStatus

func (p *ControlPlaneGetScaffoldResult) GetSuccess() (v *model.ScaffoldStatus) {
	if !p.IsSetSuccess() {
		return ControlPlaneGetScaffoldResult_Success_DEFAULT
	}
	return p.Success
}

var fieldIDToName_ControlPlaneGetScaffoldResult = map[int16]string{
	0: "success",
}

func (p *ControlPlaneGetScaffoldResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ControlPlaneGetScaffoldResult) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 0:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField0(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_ControlPlaneGetScaffoldResult[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *ControlPlaneGetScaffoldResult) ReadField0(iprot thrift.TProtocol) error {
	_field := model.NewScaffoldStatus()
	if err := _field.Read(iprot); err != nil {
		return err
	}
	p.Success = _field
	return nil
}

func (p *ControlPlaneGetScaffoldResult) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("GetScaffold_result"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField0(oprot); err != nil {
			fieldId = 0
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *ControlPlaneGetScaffoldResult) writeField0(oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err = oprot.WriteFieldBegin("success", thrift.STRUCT, 0); err != nil {
			goto WriteFieldBeginError
		}
		if err := p.Success.Write(oprot); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 0 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 0 end error: ", p), err)
}

func (p *ControlPlaneGetScaffoldResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ControlPlaneGetScaffoldResult(%+v)", *p)

}
