// Code generated by hertz generator.

package api

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _controlMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getissueMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getscaffoldMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getstateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _refreshMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _orchestratorMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _projectissuerunMw() []app.HandlerFunc {
	// your code...
	return nil
}
