// Code generated by hertz generator.

package http

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getscaffoldMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getstateMw() []app.HandlerFunc {
	// your code...
	return nil
}
