// Code generated by thriftgo (0.2.7). DO NOT EDIT.

package api

import (
	"context"
	"fmt"
	"github.com/apache/thrift/lib/go/thrift"
	"github.com/zeefan1555/symphony-go/biz/model/control"
	"github.com/zeefan1555/symphony-go/biz/model/orchestrator"
)

type SymphonyAPI interface {
	GetScaffold(ctx context.Context, req *control.GetScaffoldReq) (r *control.GetScaffoldResp, err error)

	GetState(ctx context.Context, req *control.GetStateReq) (r *control.GetStateResp, err error)

	Refresh(ctx context.Context, req *control.RefreshReq) (r *control.RefreshResp, err error)

	GetIssue(ctx context.Context, req *control.GetIssueReq) (r *control.GetIssueResp, err error)

	ProjectIssueRun(ctx context.Context, req *orchestrator.ProjectIssueRunReq) (r *orchestrator.ProjectIssueRunResp, err error)
}

type SymphonyAPIClient struct {
	c thrift.TClient
}

func NewSymphonyAPIClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *SymphonyAPIClient {
	return &SymphonyAPIClient{
		c: thrift.NewTStandardClient(f.GetProtocol(t), f.GetProtocol(t)),
	}
}

func NewSymphonyAPIClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *SymphonyAPIClient {
	return &SymphonyAPIClient{
		c: thrift.NewTStandardClient(iprot, oprot),
	}
}

func NewSymphonyAPIClient(c thrift.TClient) *SymphonyAPIClient {
	return &SymphonyAPIClient{
		c: c,
	}
}

func (p *SymphonyAPIClient) Client_() thrift.TClient {
	return p.c
}

func (p *SymphonyAPIClient) GetScaffold(ctx context.Context, req *control.GetScaffoldReq) (r *control.GetScaffoldResp, err error) {
	var _args SymphonyAPIGetScaffoldArgs
	_args.Req = req
	var _result SymphonyAPIGetScaffoldResult
	if err = p.Client_().Call(ctx, "GetScaffold", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
func (p *SymphonyAPIClient) GetState(ctx context.Context, req *control.GetStateReq) (r *control.GetStateResp, err error) {
	var _args SymphonyAPIGetStateArgs
	_args.Req = req
	var _result SymphonyAPIGetStateResult
	if err = p.Client_().Call(ctx, "GetState", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
func (p *SymphonyAPIClient) Refresh(ctx context.Context, req *control.RefreshReq) (r *control.RefreshResp, err error) {
	var _args SymphonyAPIRefreshArgs
	_args.Req = req
	var _result SymphonyAPIRefreshResult
	if err = p.Client_().Call(ctx, "Refresh", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
func (p *SymphonyAPIClient) GetIssue(ctx context.Context, req *control.GetIssueReq) (r *control.GetIssueResp, err error) {
	var _args SymphonyAPIGetIssueArgs
	_args.Req = req
	var _result SymphonyAPIGetIssueResult
	if err = p.Client_().Call(ctx, "GetIssue", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
func (p *SymphonyAPIClient) ProjectIssueRun(ctx context.Context, req *orchestrator.ProjectIssueRunReq) (r *orchestrator.ProjectIssueRunResp, err error) {
	var _args SymphonyAPIProjectIssueRunArgs
	_args.Req = req
	var _result SymphonyAPIProjectIssueRunResult
	if err = p.Client_().Call(ctx, "ProjectIssueRun", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

type SymphonyAPIProcessor struct {
	processorMap map[string]thrift.TProcessorFunction
	handler      SymphonyAPI
}

func (p *SymphonyAPIProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
	p.processorMap[key] = processor
}

func (p *SymphonyAPIProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
	processor, ok = p.processorMap[key]
	return processor, ok
}

func (p *SymphonyAPIProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
	return p.processorMap
}

func NewSymphonyAPIProcessor(handler SymphonyAPI) *SymphonyAPIProcessor {
	self := &SymphonyAPIProcessor{handler: handler, processorMap: make(map[string]thrift.TProcessorFunction)}
	self.AddToProcessorMap("GetScaffold", &symphonyAPIProcessorGetScaffold{handler: handler})
	self.AddToProcessorMap("GetState", &symphonyAPIProcessorGetState{handler: handler})
	self.AddToProcessorMap("Refresh", &symphonyAPIProcessorRefresh{handler: handler})
	self.AddToProcessorMap("GetIssue", &symphonyAPIProcessorGetIssue{handler: handler})
	self.AddToProcessorMap("ProjectIssueRun", &symphonyAPIProcessorProjectIssueRun{handler: handler})
	return self
}
func (p *SymphonyAPIProcessor) Process(ctx context.Context, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	name, _, seqId, err := iprot.ReadMessageBegin()
	if err != nil {
		return false, err
	}
	if processor, ok := p.GetProcessorFunction(name); ok {
		return processor.Process(ctx, seqId, iprot, oprot)
	}
	iprot.Skip(thrift.STRUCT)
	iprot.ReadMessageEnd()
	x := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function "+name)
	oprot.WriteMessageBegin(name, thrift.EXCEPTION, seqId)
	x.Write(oprot)
	oprot.WriteMessageEnd()
	oprot.Flush(ctx)
	return false, x
}

type symphonyAPIProcessorGetScaffold struct {
	handler SymphonyAPI
}

func (p *symphonyAPIProcessorGetScaffold) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	args := SymphonyAPIGetScaffoldArgs{}
	if err = args.Read(iprot); err != nil {
		iprot.ReadMessageEnd()
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
		oprot.WriteMessageBegin("GetScaffold", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return false, err
	}

	iprot.ReadMessageEnd()
	var err2 error
	result := SymphonyAPIGetScaffoldResult{}
	var retval *control.GetScaffoldResp
	if retval, err2 = p.handler.GetScaffold(ctx, args.Req); err2 != nil {
		x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing GetScaffold: "+err2.Error())
		oprot.WriteMessageBegin("GetScaffold", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return true, err2
	} else {
		result.Success = retval
	}
	if err2 = oprot.WriteMessageBegin("GetScaffold", thrift.REPLY, seqId); err2 != nil {
		err = err2
	}
	if err2 = result.Write(oprot); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.Flush(ctx); err == nil && err2 != nil {
		err = err2
	}
	if err != nil {
		return
	}
	return true, err
}

type symphonyAPIProcessorGetState struct {
	handler SymphonyAPI
}

func (p *symphonyAPIProcessorGetState) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	args := SymphonyAPIGetStateArgs{}
	if err = args.Read(iprot); err != nil {
		iprot.ReadMessageEnd()
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
		oprot.WriteMessageBegin("GetState", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return false, err
	}

	iprot.ReadMessageEnd()
	var err2 error
	result := SymphonyAPIGetStateResult{}
	var retval *control.GetStateResp
	if retval, err2 = p.handler.GetState(ctx, args.Req); err2 != nil {
		x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing GetState: "+err2.Error())
		oprot.WriteMessageBegin("GetState", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return true, err2
	} else {
		result.Success = retval
	}
	if err2 = oprot.WriteMessageBegin("GetState", thrift.REPLY, seqId); err2 != nil {
		err = err2
	}
	if err2 = result.Write(oprot); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.Flush(ctx); err == nil && err2 != nil {
		err = err2
	}
	if err != nil {
		return
	}
	return true, err
}

type symphonyAPIProcessorRefresh struct {
	handler SymphonyAPI
}

func (p *symphonyAPIProcessorRefresh) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	args := SymphonyAPIRefreshArgs{}
	if err = args.Read(iprot); err != nil {
		iprot.ReadMessageEnd()
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
		oprot.WriteMessageBegin("Refresh", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return false, err
	}

	iprot.ReadMessageEnd()
	var err2 error
	result := SymphonyAPIRefreshResult{}
	var retval *control.RefreshResp
	if retval, err2 = p.handler.Refresh(ctx, args.Req); err2 != nil {
		x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing Refresh: "+err2.Error())
		oprot.WriteMessageBegin("Refresh", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return true, err2
	} else {
		result.Success = retval
	}
	if err2 = oprot.WriteMessageBegin("Refresh", thrift.REPLY, seqId); err2 != nil {
		err = err2
	}
	if err2 = result.Write(oprot); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.Flush(ctx); err == nil && err2 != nil {
		err = err2
	}
	if err != nil {
		return
	}
	return true, err
}

type symphonyAPIProcessorGetIssue struct {
	handler SymphonyAPI
}

func (p *symphonyAPIProcessorGetIssue) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	args := SymphonyAPIGetIssueArgs{}
	if err = args.Read(iprot); err != nil {
		iprot.ReadMessageEnd()
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
		oprot.WriteMessageBegin("GetIssue", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return false, err
	}

	iprot.ReadMessageEnd()
	var err2 error
	result := SymphonyAPIGetIssueResult{}
	var retval *control.GetIssueResp
	if retval, err2 = p.handler.GetIssue(ctx, args.Req); err2 != nil {
		x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing GetIssue: "+err2.Error())
		oprot.WriteMessageBegin("GetIssue", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return true, err2
	} else {
		result.Success = retval
	}
	if err2 = oprot.WriteMessageBegin("GetIssue", thrift.REPLY, seqId); err2 != nil {
		err = err2
	}
	if err2 = result.Write(oprot); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.Flush(ctx); err == nil && err2 != nil {
		err = err2
	}
	if err != nil {
		return
	}
	return true, err
}

type symphonyAPIProcessorProjectIssueRun struct {
	handler SymphonyAPI
}

func (p *symphonyAPIProcessorProjectIssueRun) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	args := SymphonyAPIProjectIssueRunArgs{}
	if err = args.Read(iprot); err != nil {
		iprot.ReadMessageEnd()
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
		oprot.WriteMessageBegin("ProjectIssueRun", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return false, err
	}

	iprot.ReadMessageEnd()
	var err2 error
	result := SymphonyAPIProjectIssueRunResult{}
	var retval *orchestrator.ProjectIssueRunResp
	if retval, err2 = p.handler.ProjectIssueRun(ctx, args.Req); err2 != nil {
		x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing ProjectIssueRun: "+err2.Error())
		oprot.WriteMessageBegin("ProjectIssueRun", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return true, err2
	} else {
		result.Success = retval
	}
	if err2 = oprot.WriteMessageBegin("ProjectIssueRun", thrift.REPLY, seqId); err2 != nil {
		err = err2
	}
	if err2 = result.Write(oprot); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.Flush(ctx); err == nil && err2 != nil {
		err = err2
	}
	if err != nil {
		return
	}
	return true, err
}

type SymphonyAPIGetScaffoldArgs struct {
	Req *control.GetScaffoldReq `thrift:"req,1"`
}

func NewSymphonyAPIGetScaffoldArgs() *SymphonyAPIGetScaffoldArgs {
	return &SymphonyAPIGetScaffoldArgs{}
}

var SymphonyAPIGetScaffoldArgs_Req_DEFAULT *control.GetScaffoldReq

func (p *SymphonyAPIGetScaffoldArgs) GetReq() (v *control.GetScaffoldReq) {
	if !p.IsSetReq() {
		return SymphonyAPIGetScaffoldArgs_Req_DEFAULT
	}
	return p.Req
}

var fieldIDToName_SymphonyAPIGetScaffoldArgs = map[int16]string{
	1: "req",
}

func (p *SymphonyAPIGetScaffoldArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SymphonyAPIGetScaffoldArgs) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}

		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_SymphonyAPIGetScaffoldArgs[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *SymphonyAPIGetScaffoldArgs) ReadField1(iprot thrift.TProtocol) error {
	p.Req = control.NewGetScaffoldReq()
	if err := p.Req.Read(iprot); err != nil {
		return err
	}
	return nil
}

func (p *SymphonyAPIGetScaffoldArgs) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("GetScaffold_args"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}

	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *SymphonyAPIGetScaffoldArgs) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("req", thrift.STRUCT, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := p.Req.Write(oprot); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *SymphonyAPIGetScaffoldArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SymphonyAPIGetScaffoldArgs(%+v)", *p)
}

type SymphonyAPIGetScaffoldResult struct {
	Success *control.GetScaffoldResp `thrift:"success,0,optional"`
}

func NewSymphonyAPIGetScaffoldResult() *SymphonyAPIGetScaffoldResult {
	return &SymphonyAPIGetScaffoldResult{}
}

var SymphonyAPIGetScaffoldResult_Success_DEFAULT *control.GetScaffoldResp

func (p *SymphonyAPIGetScaffoldResult) GetSuccess() (v *control.GetScaffoldResp) {
	if !p.IsSetSuccess() {
		return SymphonyAPIGetScaffoldResult_Success_DEFAULT
	}
	return p.Success
}

var fieldIDToName_SymphonyAPIGetScaffoldResult = map[int16]string{
	0: "success",
}

func (p *SymphonyAPIGetScaffoldResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SymphonyAPIGetScaffoldResult) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 0:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField0(iprot); err != nil {
					goto ReadFieldError
				}
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}

		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_SymphonyAPIGetScaffoldResult[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *SymphonyAPIGetScaffoldResult) ReadField0(iprot thrift.TProtocol) error {
	p.Success = control.NewGetScaffoldResp()
	if err := p.Success.Read(iprot); err != nil {
		return err
	}
	return nil
}

func (p *SymphonyAPIGetScaffoldResult) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("GetScaffold_result"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField0(oprot); err != nil {
			fieldId = 0
			goto WriteFieldError
		}

	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *SymphonyAPIGetScaffoldResult) writeField0(oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err = oprot.WriteFieldBegin("success", thrift.STRUCT, 0); err != nil {
			goto WriteFieldBeginError
		}
		if err := p.Success.Write(oprot); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 0 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 0 end error: ", p), err)
}

func (p *SymphonyAPIGetScaffoldResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SymphonyAPIGetScaffoldResult(%+v)", *p)
}

type SymphonyAPIGetStateArgs struct {
	Req *control.GetStateReq `thrift:"req,1"`
}

func NewSymphonyAPIGetStateArgs() *SymphonyAPIGetStateArgs {
	return &SymphonyAPIGetStateArgs{}
}

var SymphonyAPIGetStateArgs_Req_DEFAULT *control.GetStateReq

func (p *SymphonyAPIGetStateArgs) GetReq() (v *control.GetStateReq) {
	if !p.IsSetReq() {
		return SymphonyAPIGetStateArgs_Req_DEFAULT
	}
	return p.Req
}

var fieldIDToName_SymphonyAPIGetStateArgs = map[int16]string{
	1: "req",
}

func (p *SymphonyAPIGetStateArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SymphonyAPIGetStateArgs) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}

		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_SymphonyAPIGetStateArgs[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *SymphonyAPIGetStateArgs) ReadField1(iprot thrift.TProtocol) error {
	p.Req = control.NewGetStateReq()
	if err := p.Req.Read(iprot); err != nil {
		return err
	}
	return nil
}

func (p *SymphonyAPIGetStateArgs) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("GetState_args"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}

	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *SymphonyAPIGetStateArgs) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("req", thrift.STRUCT, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := p.Req.Write(oprot); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *SymphonyAPIGetStateArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SymphonyAPIGetStateArgs(%+v)", *p)
}

type SymphonyAPIGetStateResult struct {
	Success *control.GetStateResp `thrift:"success,0,optional"`
}

func NewSymphonyAPIGetStateResult() *SymphonyAPIGetStateResult {
	return &SymphonyAPIGetStateResult{}
}

var SymphonyAPIGetStateResult_Success_DEFAULT *control.GetStateResp

func (p *SymphonyAPIGetStateResult) GetSuccess() (v *control.GetStateResp) {
	if !p.IsSetSuccess() {
		return SymphonyAPIGetStateResult_Success_DEFAULT
	}
	return p.Success
}

var fieldIDToName_SymphonyAPIGetStateResult = map[int16]string{
	0: "success",
}

func (p *SymphonyAPIGetStateResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SymphonyAPIGetStateResult) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 0:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField0(iprot); err != nil {
					goto ReadFieldError
				}
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}

		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_SymphonyAPIGetStateResult[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *SymphonyAPIGetStateResult) ReadField0(iprot thrift.TProtocol) error {
	p.Success = control.NewGetStateResp()
	if err := p.Success.Read(iprot); err != nil {
		return err
	}
	return nil
}

func (p *SymphonyAPIGetStateResult) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("GetState_result"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField0(oprot); err != nil {
			fieldId = 0
			goto WriteFieldError
		}

	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *SymphonyAPIGetStateResult) writeField0(oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err = oprot.WriteFieldBegin("success", thrift.STRUCT, 0); err != nil {
			goto WriteFieldBeginError
		}
		if err := p.Success.Write(oprot); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 0 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 0 end error: ", p), err)
}

func (p *SymphonyAPIGetStateResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SymphonyAPIGetStateResult(%+v)", *p)
}

type SymphonyAPIRefreshArgs struct {
	Req *control.RefreshReq `thrift:"req,1"`
}

func NewSymphonyAPIRefreshArgs() *SymphonyAPIRefreshArgs {
	return &SymphonyAPIRefreshArgs{}
}

var SymphonyAPIRefreshArgs_Req_DEFAULT *control.RefreshReq

func (p *SymphonyAPIRefreshArgs) GetReq() (v *control.RefreshReq) {
	if !p.IsSetReq() {
		return SymphonyAPIRefreshArgs_Req_DEFAULT
	}
	return p.Req
}

var fieldIDToName_SymphonyAPIRefreshArgs = map[int16]string{
	1: "req",
}

func (p *SymphonyAPIRefreshArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SymphonyAPIRefreshArgs) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}

		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_SymphonyAPIRefreshArgs[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *SymphonyAPIRefreshArgs) ReadField1(iprot thrift.TProtocol) error {
	p.Req = control.NewRefreshReq()
	if err := p.Req.Read(iprot); err != nil {
		return err
	}
	return nil
}

func (p *SymphonyAPIRefreshArgs) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("Refresh_args"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}

	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *SymphonyAPIRefreshArgs) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("req", thrift.STRUCT, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := p.Req.Write(oprot); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *SymphonyAPIRefreshArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SymphonyAPIRefreshArgs(%+v)", *p)
}

type SymphonyAPIRefreshResult struct {
	Success *control.RefreshResp `thrift:"success,0,optional"`
}

func NewSymphonyAPIRefreshResult() *SymphonyAPIRefreshResult {
	return &SymphonyAPIRefreshResult{}
}

var SymphonyAPIRefreshResult_Success_DEFAULT *control.RefreshResp

func (p *SymphonyAPIRefreshResult) GetSuccess() (v *control.RefreshResp) {
	if !p.IsSetSuccess() {
		return SymphonyAPIRefreshResult_Success_DEFAULT
	}
	return p.Success
}

var fieldIDToName_SymphonyAPIRefreshResult = map[int16]string{
	0: "success",
}

func (p *SymphonyAPIRefreshResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SymphonyAPIRefreshResult) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 0:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField0(iprot); err != nil {
					goto ReadFieldError
				}
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}

		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_SymphonyAPIRefreshResult[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *SymphonyAPIRefreshResult) ReadField0(iprot thrift.TProtocol) error {
	p.Success = control.NewRefreshResp()
	if err := p.Success.Read(iprot); err != nil {
		return err
	}
	return nil
}

func (p *SymphonyAPIRefreshResult) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("Refresh_result"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField0(oprot); err != nil {
			fieldId = 0
			goto WriteFieldError
		}

	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *SymphonyAPIRefreshResult) writeField0(oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err = oprot.WriteFieldBegin("success", thrift.STRUCT, 0); err != nil {
			goto WriteFieldBeginError
		}
		if err := p.Success.Write(oprot); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 0 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 0 end error: ", p), err)
}

func (p *SymphonyAPIRefreshResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SymphonyAPIRefreshResult(%+v)", *p)
}

type SymphonyAPIGetIssueArgs struct {
	Req *control.GetIssueReq `thrift:"req,1"`
}

func NewSymphonyAPIGetIssueArgs() *SymphonyAPIGetIssueArgs {
	return &SymphonyAPIGetIssueArgs{}
}

var SymphonyAPIGetIssueArgs_Req_DEFAULT *control.GetIssueReq

func (p *SymphonyAPIGetIssueArgs) GetReq() (v *control.GetIssueReq) {
	if !p.IsSetReq() {
		return SymphonyAPIGetIssueArgs_Req_DEFAULT
	}
	return p.Req
}

var fieldIDToName_SymphonyAPIGetIssueArgs = map[int16]string{
	1: "req",
}

func (p *SymphonyAPIGetIssueArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SymphonyAPIGetIssueArgs) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}

		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_SymphonyAPIGetIssueArgs[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *SymphonyAPIGetIssueArgs) ReadField1(iprot thrift.TProtocol) error {
	p.Req = control.NewGetIssueReq()
	if err := p.Req.Read(iprot); err != nil {
		return err
	}
	return nil
}

func (p *SymphonyAPIGetIssueArgs) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("GetIssue_args"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}

	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *SymphonyAPIGetIssueArgs) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("req", thrift.STRUCT, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := p.Req.Write(oprot); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *SymphonyAPIGetIssueArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SymphonyAPIGetIssueArgs(%+v)", *p)
}

type SymphonyAPIGetIssueResult struct {
	Success *control.GetIssueResp `thrift:"success,0,optional"`
}

func NewSymphonyAPIGetIssueResult() *SymphonyAPIGetIssueResult {
	return &SymphonyAPIGetIssueResult{}
}

var SymphonyAPIGetIssueResult_Success_DEFAULT *control.GetIssueResp

func (p *SymphonyAPIGetIssueResult) GetSuccess() (v *control.GetIssueResp) {
	if !p.IsSetSuccess() {
		return SymphonyAPIGetIssueResult_Success_DEFAULT
	}
	return p.Success
}

var fieldIDToName_SymphonyAPIGetIssueResult = map[int16]string{
	0: "success",
}

func (p *SymphonyAPIGetIssueResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SymphonyAPIGetIssueResult) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 0:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField0(iprot); err != nil {
					goto ReadFieldError
				}
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}

		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_SymphonyAPIGetIssueResult[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *SymphonyAPIGetIssueResult) ReadField0(iprot thrift.TProtocol) error {
	p.Success = control.NewGetIssueResp()
	if err := p.Success.Read(iprot); err != nil {
		return err
	}
	return nil
}

func (p *SymphonyAPIGetIssueResult) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("GetIssue_result"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField0(oprot); err != nil {
			fieldId = 0
			goto WriteFieldError
		}

	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *SymphonyAPIGetIssueResult) writeField0(oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err = oprot.WriteFieldBegin("success", thrift.STRUCT, 0); err != nil {
			goto WriteFieldBeginError
		}
		if err := p.Success.Write(oprot); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 0 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 0 end error: ", p), err)
}

func (p *SymphonyAPIGetIssueResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SymphonyAPIGetIssueResult(%+v)", *p)
}

type SymphonyAPIProjectIssueRunArgs struct {
	Req *orchestrator.ProjectIssueRunReq `thrift:"req,1"`
}

func NewSymphonyAPIProjectIssueRunArgs() *SymphonyAPIProjectIssueRunArgs {
	return &SymphonyAPIProjectIssueRunArgs{}
}

var SymphonyAPIProjectIssueRunArgs_Req_DEFAULT *orchestrator.ProjectIssueRunReq

func (p *SymphonyAPIProjectIssueRunArgs) GetReq() (v *orchestrator.ProjectIssueRunReq) {
	if !p.IsSetReq() {
		return SymphonyAPIProjectIssueRunArgs_Req_DEFAULT
	}
	return p.Req
}

var fieldIDToName_SymphonyAPIProjectIssueRunArgs = map[int16]string{
	1: "req",
}

func (p *SymphonyAPIProjectIssueRunArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SymphonyAPIProjectIssueRunArgs) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}

		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_SymphonyAPIProjectIssueRunArgs[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *SymphonyAPIProjectIssueRunArgs) ReadField1(iprot thrift.TProtocol) error {
	p.Req = orchestrator.NewProjectIssueRunReq()
	if err := p.Req.Read(iprot); err != nil {
		return err
	}
	return nil
}

func (p *SymphonyAPIProjectIssueRunArgs) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("ProjectIssueRun_args"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}

	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *SymphonyAPIProjectIssueRunArgs) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("req", thrift.STRUCT, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := p.Req.Write(oprot); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *SymphonyAPIProjectIssueRunArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SymphonyAPIProjectIssueRunArgs(%+v)", *p)
}

type SymphonyAPIProjectIssueRunResult struct {
	Success *orchestrator.ProjectIssueRunResp `thrift:"success,0,optional"`
}

func NewSymphonyAPIProjectIssueRunResult() *SymphonyAPIProjectIssueRunResult {
	return &SymphonyAPIProjectIssueRunResult{}
}

var SymphonyAPIProjectIssueRunResult_Success_DEFAULT *orchestrator.ProjectIssueRunResp

func (p *SymphonyAPIProjectIssueRunResult) GetSuccess() (v *orchestrator.ProjectIssueRunResp) {
	if !p.IsSetSuccess() {
		return SymphonyAPIProjectIssueRunResult_Success_DEFAULT
	}
	return p.Success
}

var fieldIDToName_SymphonyAPIProjectIssueRunResult = map[int16]string{
	0: "success",
}

func (p *SymphonyAPIProjectIssueRunResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SymphonyAPIProjectIssueRunResult) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 0:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField0(iprot); err != nil {
					goto ReadFieldError
				}
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}

		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_SymphonyAPIProjectIssueRunResult[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *SymphonyAPIProjectIssueRunResult) ReadField0(iprot thrift.TProtocol) error {
	p.Success = orchestrator.NewProjectIssueRunResp()
	if err := p.Success.Read(iprot); err != nil {
		return err
	}
	return nil
}

func (p *SymphonyAPIProjectIssueRunResult) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("ProjectIssueRun_result"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField0(oprot); err != nil {
			fieldId = 0
			goto WriteFieldError
		}

	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *SymphonyAPIProjectIssueRunResult) writeField0(oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err = oprot.WriteFieldBegin("success", thrift.STRUCT, 0); err != nil {
			goto WriteFieldBeginError
		}
		if err := p.Success.Write(oprot); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 0 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 0 end error: ", p), err)
}

func (p *SymphonyAPIProjectIssueRunResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SymphonyAPIProjectIssueRunResult(%+v)", *p)
}
