#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
go_cmd="${GO:-go}"
export PATH="$("$go_cmd" env GOPATH)/bin:${PATH}"

if ! command -v hz >/dev/null 2>&1; then
  echo "hz not found. Install with: go install -ldflags=-linkmode=external github.com/cloudwego/hertz/cmd/hz@v0.9.7" >&2
  exit 1
fi

if ! command -v thriftgo >/dev/null 2>&1; then
  echo "thriftgo not found. Install with: go install github.com/cloudwego/thriftgo@latest" >&2
  exit 1
fi

tmp_dir="$(mktemp -d)"
cleanup() {
  rm -rf "$tmp_dir"
}
trap cleanup EXIT

hz new \
  --module github.com/zeefan1555/symphony-go \
  --out_dir "$tmp_dir" \
  --handler_dir gen/hertz/handler \
  --model_dir gen/hertz/model \
  --idl "$repo_root/idl/main.thrift"

find "$tmp_dir/biz/router" -type f -name '*.go' -exec perl -pi -e 's/^package Api$/package api/' {} +

rm -rf "$repo_root/gen/hertz/handler" "$repo_root/gen/hertz/model" "$repo_root/gen/hertz/router"
mkdir -p "$repo_root/gen/hertz"
cp -R "$tmp_dir/gen/hertz/handler" "$repo_root/gen/hertz/handler"
cp -R "$tmp_dir/gen/hertz/model" "$repo_root/gen/hertz/model"
cp -R "$tmp_dir/biz/router" "$repo_root/gen/hertz/router"
if [ -f "$tmp_dir/biz/handler/ping.go" ]; then
  cp "$tmp_dir/biz/handler/ping.go" "$repo_root/gen/hertz/handler/ping.go"
fi

find "$repo_root/gen/hertz" -type f -name '*.go' -exec perl -pi -e 's#github\.com/zeefan1555/symphony-go/biz/#github.com/zeefan1555/symphony-go/gen/hertz/#g' {} +

if [ -f "$repo_root/gen/hertz/router/register.go" ]; then
  perl -0pi -e 's/\n\tcontrol_http "github\.com\/zeefan1555\/symphony-go\/gen\/hertz\/router\/control\/http"\n/\n/' "$repo_root/gen/hertz/router/register.go"
  perl -0pi -e 's/\n\tcontrol_http\.Register\(r\)\n/\n/' "$repo_root/gen/hertz/router/register.go"
else
  cat > "$repo_root/gen/hertz/router/register.go" <<'REGISTER_EOF'
// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	api "github.com/zeefan1555/symphony-go/gen/hertz/router/api"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	api.Register(r)
}
REGISTER_EOF
fi

find "$repo_root/gen/hertz" -type f -name '*.go' -exec perl -pi -e 's/[ \t]+$//' {} +
find "$repo_root/gen/hertz" -type f -name '*.go' -exec chmod 0644 {} +
