#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
go_cmd="${GO:-go}"
module_name="symphony-go"
export PATH="$("$go_cmd" env GOPATH)/bin:${PATH}"

if ! command -v hz >/dev/null 2>&1; then
  echo "hz not found. Install with: go install -ldflags=-linkmode=external github.com/cloudwego/hertz/cmd/hz@v0.9.7" >&2
  exit 1
fi

if ! command -v buf >/dev/null 2>&1; then
  echo "buf not found. Install with: go install github.com/bufbuild/buf/cmd/buf@latest" >&2
  exit 1
fi

if ! command -v protoc >/dev/null 2>&1; then
  echo "protoc not found. Install with: brew install protobuf" >&2
  exit 1
fi

if ! command -v protoc-gen-go >/dev/null 2>&1; then
  echo "protoc-gen-go not found. Install with: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest" >&2
  exit 1
fi

cd "$repo_root"
buf lint

tmp_dir="$(mktemp -d)"
cleanup() {
  rm -rf "$tmp_dir"
}
trap cleanup EXIT

hz new \
  --module "$module_name" \
  --out_dir "$tmp_dir" \
  -I "$repo_root/idl" \
  --handler_dir gen/hertz/handler \
  --model_dir gen/hertz/model \
  --idl "$repo_root/idl/main.proto"

find "$tmp_dir/biz/router" -type f -name '*.go' -exec perl -pi -e 's/^package Api$/package api/' {} +

rm -rf "$repo_root/gen/hertz/handler" "$repo_root/gen/hertz/model" "$repo_root/gen/hertz/router"
mkdir -p "$repo_root/gen/hertz"
cp -R "$tmp_dir/gen/hertz/handler" "$repo_root/gen/hertz/handler"
cp -R "$tmp_dir/gen/hertz/model" "$repo_root/gen/hertz/model"
cp -R "$tmp_dir/biz/router" "$repo_root/gen/hertz/router"
if [ -f "$tmp_dir/biz/handler/ping.go" ]; then
  cp "$tmp_dir/biz/handler/ping.go" "$repo_root/gen/hertz/handler/ping.go"
fi

old_remote="github.com/zeefan1555/${module_name}/biz/"
old_local="${module_name}/biz/"
new_import="${module_name}/gen/hertz/"
export old_remote old_local new_import
find "$repo_root/gen/hertz" -type f -name '*.go' -exec perl -pi -e 's#\Q$ENV{old_remote}\E#$ENV{new_import}#g; s#\Q$ENV{old_local}\E#$ENV{new_import}#g' {} +
while IFS= read -r file; do
  mv "$file" "${file%.pb.go}.go"
done < <(find "$repo_root/gen/hertz/model" -type f -name '*.pb.go' | sort)
find "$repo_root/gen/hertz/model" -type f -name '*.go' -exec perl -pi -e 's/\bIssueId\b/IssueID/g; s/\bGetIssueId\b/GetIssueID/g; s/\bSessionId\b/SessionID/g; s/\bGetSessionId\b/GetSessionID/g; s/json:"(running|retrying),omitempty"/json:"$1"/g' {} +

handler_file="$repo_root/gen/hertz/handler/api/symphony_api.go"
perl -0pi -e 's#// GetIssueFlow \.\n// \@router /api/v1/orchestrator/get-issue-flow \[POST\]\nfunc GetIssueFlow\(ctx context.Context, c \*app.RequestContext\) \{.*?\n\}\n\z#// GetIssueFlow .\n// \@router /api/v1/orchestrator/get-issue-flow [POST]\nfunc GetIssueFlow(ctx context.Context, c *app.RequestContext) {\n\tvar err error\n\tvar req orchestrator.GetIssueFlowReq\n\terr = c.BindAndValidate(&req)\n\tif err != nil {\n\t\tc.JSON(consts.StatusBadRequest, &common.ErrorEnvelope{Error: &common.ErrorDetail{\n\t\t\tCode:    "invalid_orchestrator_request",\n\t\t\tMessage: err.Error(),\n\t\t}})\n\t\treturn\n\t}\n\n\tresp, err := hertzbinding.CurrentService().GetIssueFlow(ctx)\n\tif err != nil {\n\t\tenvelope, status := hertzbinding.ErrorEnvelope(err)\n\t\tc.JSON(status, envelope)\n\t\treturn\n\t}\n\n\tc.JSON(consts.StatusOK, resp)\n}\n#s' "$handler_file"

if [ -f "$repo_root/gen/hertz/router/register.go" ]; then
  perl -0pi -e 's/\n\tcontrol_http "(?:github\.com\/zeefan1555\/symphony-go|symphony-go)\/gen\/hertz\/router\/control\/http"\n/\n/' "$repo_root/gen/hertz/router/register.go"
  perl -0pi -e 's/\n\tcontrol_http\.Register\(r\)\n/\n/' "$repo_root/gen/hertz/router/register.go"
else
  cat > "$repo_root/gen/hertz/router/register.go" <<'REGISTER_EOF'
// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	api "symphony-go/gen/hertz/router/api"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	api.Register(r)
}
REGISTER_EOF
fi

find "$repo_root/gen/hertz" -type f -name '*.go' -exec perl -pi -e 's/[ \t]+$//' {} +
find "$repo_root/gen/hertz" -type f -name '*.go' -exec chmod 0644 {} +
